# FIRST QUESTION

In [2]:
import numpy as np

In [16]:
x=np.genfromtxt(r"D:\work\tipsf.csv",delimiter=",",skip_header=1)

In [5]:
x

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

# 1. What is the total bill value?

In [4]:
np.sum(x[:,1])

4827.77

# 2. What is the total tip value?

In [5]:
np.sum(x[:,2])

731.5799999999999

# 3. Count how many sun,sat,thu,fri are there.

In [9]:
x1=np.unique(x[:,5],return_counts=True)
a,s=x1
y=0
for i in a:
    if(i==0):
        print("sun = ",s[y])
        y+=1
    elif(i==1):
        print("sat = ",s[y])
        y+=1
    elif(i==2):
        print("thu = ",s[y])
        y+=1
    else:
        print("fri = ",s[y])
        y+=1    

sun =  87
sat =  76
thu =  62
fri =  19


# 4. How many smokers are there?

In [10]:
np.sum(x[:,4])

93.0

# 5. What is the avg tip given by females and males?

In [13]:
x1=np.sum(x[:,2].take(np.where(x[:,3]==0)))
x2=np.sum(x[:,2].take(np.where(x[:,3]==1)))
y=np.unique(x[:,3],return_counts=True)
q,z=y
print(x1/z[0],"avg tip by female")
print(x1/z[1],"avg tip by male")

2.8334482758620685 avg tip by female
1.5701273885350315 avg tip by male


# 6. How much amount has been spent by male and female?

In [18]:
y1=np.sum(x[:,1].take(np.where(x[:,3]==0))
y2=np.sum(x[:,1].take(np.where(x[:,3]==1))
print(y1,"= amount spent by females")
print(y2,"= amount spent by males")              

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1016720444.py, line 1)

# 7. What is the min and max tip?

In [14]:
np.max(x[:,2])

10.0

In [16]:
np.min(x[:,2])

1.0

# 8. How many male and female are going for dinner and lunch?

In [19]:
x1=np.unique(x[:,3].take(np.where((x[:,6]==1))),return_counts=True)      
a,b=x1
x2=np.unique(x[:,3].take(np.where((x[:,6]==0))),return_counts=True)      
c,d=x2
for i in a:
    if(i==0):
        print("total female going for lunch",b[0])
        print("total female going for dinner",d[0])
    else:
         print("total male going for lunch",b[1])
         print("total female going for dinner",d[1])

total female going for lunch 35
total female going for dinner 52
total male going for lunch 33
total female going for dinner 124


# 9. Find out the avg size

In [17]:
np.mean(x[:,7])

2.569672131147541

# 10. How many female and male smokers are there?

In [24]:
x1=np.unique(x[:,3].take(np.where(x[:,4]==1)),return_counts=True)
a,b=x1
for i in a:
    if (i==0):
        print("Female smokers : ",b[0])
    else:
        print("Male smokers : ",b[1])

Female smokers :  33
Male smokers :  60


# SECOND QUESTION

In [25]:
y=np.genfromtxt(r"D:\work\train_extended.csv",delimiter=",",skip_header=1)

In [26]:
y

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

# 1.What is max and min length?

In [24]:
np.max(y[:,0])

7.58349125

In [25]:
np.min(y[:,0])

0.0

# 2. Difference between max and min length

In [26]:
a=np.max(y[:,0])-np.min(y[:,0])

In [27]:
a

7.58349125

# 3.Find column wise average

In [28]:
b=np.mean(y,axis=0)

In [29]:
b

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

# 4.Find out all the age whose height is greater than 0.4

In [32]:
x1=y[:,7].take(np.where(x[:,2]>0.4))

In [33]:
x1

array([[10., 19., 11.,  9.,  8., 10., 14., 13.,  9., 10., 10.,  6.,  9.,
         7., 14., 16., 19.,  9.,  9.,  9., 12.,  6., 13.,  9.,  9., 11.,
         9.,  8., 10.,  9., 20., 11., 17.,  8.,  5.,  9.,  8.,  5., 15.,
         7., 12., 11.,  8., 11., 12.,  8.,  9., 14., 15.,  9.,  5.,  8.,
        11.,  5., 11.,  8., 13., 11.,  9., 11.,  7.,  7.,  8., 10., 11.,
         9., 13.,  8.,  7.,  7., 10.,  9.,  6.,  4.,  8., 10., 10., 10.,
        10.,  8., 10.,  8.,  8., 10.,  9., 11.,  9.,  7., 13.,  9.,  6.,
        12., 14., 11.,  9., 11., 10.,  8., 11., 15., 10.,  8.,  9.,  5.,
         8.,  9., 11., 11.,  8., 12.,  8., 10.,  7.,  8., 10., 12., 10.,
        13.,  9., 10., 10.,  4.,  6.,  7.,  9.,  4., 10., 16., 10.,  7.,
        14.,  6., 10., 10.,  8., 11., 12.,  9., 11., 17., 10.,  4.,  8.,
        15.,  6., 10.,  7., 10., 11.,  6., 14.,  6., 11., 11., 12.,  3.,
        10.,  7., 10., 11., 11., 13.,  8.,  8.,  8., 10., 16., 11., 11.,
        12., 10.,  6.,  9.,  7., 22., 11., 14., 11.

# 5. Avg height,weight whose age is 10

In [41]:
x1=np.array(y[:,2].take(np.where(y[:,7]==10)))
print("avg height whose age is 10 = ",np.mean(x1))
x1=np.array(y[:,3].take(np.where(y[:,7]==10)))
print("avg weight whose age is 10 = ",np.mean(x1))

avg height whose age is 10 =  0.3833672856539947
avg weight whose age is 10 =  28.243308450511314


# 6. What is total shell weight?


In [42]:
np.sum(y[:,6])

1326845.8295214002

# 7. How many people belongs to each and every unique age

In [45]:
x1=np.unique(y[:,7],return_counts=True)

In [46]:
x1

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

# 8. Difference b/w shuckled and viscera weight

In [47]:
x1=np.sum(y[:,4])
x2=np.sum(y[:,5])
print("Difference b/w shuckled and viscera weight = ",x1-x2)

Difference b/w shuckled and viscera weight =  999237.8582600503


# 9. Avg height of person whose age is greater than 14 and less than 19

In [55]:
x1=np.array(y[:,2].take(np.where((y[:,7]>14) & (y[:,7]<19))))
np.mean(x1)

0.4190701892744479

# 10 . Avg weight if we include all weights

In [58]:
x1=np.sum(y[:,3:7])

In [59]:
y.shape

(200000, 8)

In [60]:
s=list(y.shape)

In [63]:
s[0]

200000

In [64]:
print("Avg weight if we include all weights = ",x1/s[0])

Avg weight if we include all weights =  44.740216665387145
