#  1) Write a program to create a 5 dimensional array with all zeros and ones


In [9]:
import numpy as np

In [7]:
x1=np.ones((1,1,1,5,4),dtype=int)

In [8]:
x1

array([[[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]]]])

In [5]:
x=np.zeros((1,1,1,5,4),dtype=int)

In [6]:
x

array([[[[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]]]])

# 2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)



In [12]:
a=np.array([[np.zeros([1,10])],[np.ones([1,10])],[np.full((1,10),5)]])

In [13]:
a

array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],


       [[[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]]]])

# 3) Write a program to create a 3x4 matrix filled with values from 10 to 21.


In [16]:
b=np.arange(10,22).reshape(3,4)

In [17]:
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# 4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,



In [18]:
c=np.diag([0,1,2,3,4,5,6,7,8,9])

In [19]:
c

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

# 5)Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.


In [10]:
n1=np.arange(1,17).reshape(4,4)
n2=n1[:,::-1]

In [11]:
n1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
n2

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

# 6) Write a program to reverse an array (the first element becomes the last).
Given array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]



In [21]:
d=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])

In [22]:
d[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

# 7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100


In [23]:
e=np.arange(1,101).reshape(10,10)

In [24]:
e

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [38]:
e1=e[((e>30)&(e<80))]

In [40]:
e1

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [39]:
e1[e1%5==0]

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

# 8) Write a program to create a 2D array with 1 on the border and 0 inside.


In [63]:
x=np.array([(np.ones(5,)),[1,0,0,0,1],(np.ones(5,))])

In [64]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# 10) Write a program to find common values between two arrays.
Expected Output:
array1: [10 20 40 60]
array2: [10, 30, 40,50]


In [13]:
x1=[]
x2=np.array([10,20,40,60])
x3=np.array([10,30,40,50])
for i in x2:
    for j in x3:
        if (i==j):
            x1.append(i)
print(x1)            

[10, 40]


# 11) Write a program to create an array 2d array and then reshape into 1d array


In [41]:
x1=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [42]:
x1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [44]:
x1.ndim

2

In [48]:
x1.flatten()

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])